### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by Leestronger** [Haonan-DONG/awesome_indoor_reconstruction#1]
Hello, since I am not familiar with c++, I am not sure how to implement your pipeline. I read sh in the script, but I did not find the corresponding folder, but I really want to try your pipeline. Could you please tell me the specific steps? Thank you very much!!

**Comment by Haonan-DONG** [comment]
Thanks for the interest of this project. 

**Which pipeline do you want to implement?**

1. For the pipeline of generating the depth map from the scanned point cloud, you can actucally follow the instruction in the [README.md](https://github.com/Haonan-DONG/awesome_indoor_reconstruction/tree/main/indoor_reconstrucion/DataGenerator/PointCloud2Depth).
2. For the pipeline of Poisson Reconstruction to reconstruct the mesh from a point cloud, either the [.sh file](https://github.com/Haonan-DONG/awesome_indoor_reconstruction/blob/main/indoor_reconstrucion/scripts/point2mesh.sh) in the scripts or the step [9](https://github.com/Haonan-DONG/awesome_indoor_reconstruction/blob/6fe487423ac97470d312ff3d8581729fc9ef7ec6/indoor_reconstrucion/DataGenerator/PointCloud2Depth/README.md?plain=1#LL103C1-L103C1) to [10](https://github.com/Haonan-DONG/awesome_indoor_reconstruction/blob/6fe487423ac97470d312ff3d8581729fc9ef7ec6/indoor_reconstrucion/DataGenerator/PointCloud2Depth/README.md?plain=1#L108) can be used.

**Comment by Leestronger** [comment]
Thank you for your prompt reply! 
Actually, my biggest problem is probably not knowing how to install it on Windows, I can't download dependencies like Gmap on Windows so it won't compile successfully, it looks like you are using Ubuntu. Also regarding the rebuilt pipeline I am not sure what C++ program your script is linked to, your Poisson rebuild link has failed.

**Comment by Leestronger** [comment]
Thank you very much.(*￣︶￣)

**Comment by Haonan-DONG** [comment]
1. Reload the [process](https://github.com/Haonan-DONG/awesome_indoor_reconstruction/blob/7a21e0384aa118defbca00547d3d44486577917d/indoor_reconstrucion/README.md?plain=1#L24) for compiling the Poisson Reconstruction Lib and the [corresponding scipt](https://github.com/Haonan-DONG/awesome_indoor_reconstruction/blob/main/indoor_reconstrucion/scripts/pcd2mesh.sh).
2. A demo data is also uploaded in Baidu Disk.

Please try the code in a Linux platform at present and I will add the process to build the lib on Windows in the future.

This issue is closed and you can reopen it with any question.

**Comment by Leestronger** [comment]
> 1. Reload the [process](https://github.com/Haonan-DONG/awesome_indoor_reconstruction/blob/7a21e0384aa118defbca00547d3d44486577917d/indoor_reconstrucion/README.md?plain=1#L24) for compiling the Poisson Reconstruction Lib and the [corresponding scipt](https://github.com/Haonan-DONG/awesome_indoor_reconstruction/blob/main/indoor_reconstrucion/scripts/pcd2mesh.sh).
> 2. A demo data is also uploaded in Baidu Disk.
> 
> Please try the code in a Linux platform at present and I will add the process to build the lib on Windows in the future.
> 
> This issue is closed and you can reopen it with any question.

thank！
 I have tried it in a Virtual machine， and I have a question while reading the example, about the normal vector, I see that it reads into the scan_alignment.mlp file, It seems to be a meshlab project with scan1 and scan2 registration aligned. Is it necessary to enter a pair of ply projects when calculating normal vectors? It seems unable to perform normal vector calculations on a single .ply file.

**Comment by Haonan-DONG** [comment]
> > 1. Reload the [process](https://github.com/Haonan-DONG/awesome_indoor_reconstruction/blob/7a21e0384aa118defbca00547d3d44486577917d/indoor_reconstrucion/README.md?plain=1#L24) for compiling the Poisson Reconstruction Lib and the [corresponding scipt](https://github.com/Haonan-DONG/awesome_indoor_reconstruction/blob/main/indoor_reconstrucion/scripts/pcd2mesh.sh).
> > 2. A demo data is also uploaded in Baidu Disk.
> > 
> > Please try the code in a Linux platform at present and I will add the process to build the lib on Windows in the future.
> > This issue is closed and you can reopen it with any question.
> 
> thank！ I have tried it in a Virtual machine， and I have a question while reading the example, about the normal vector, I see that it reads into the scan_alignment.mlp file, It seems to be a meshlab project with scan1 and scan2 registration aligned. Is it necessary to enter a pair of ply projects when calculating normal vectors? It seems unable to perform normal vector calculations on a single .ply file.

It is a meshlab project to align multiple point clouds and it also works with even one single point cloud, following the [README.md](https://github.com/Haonan-DONG/awesome_indoor_reconstruction/blob/main/indoor_reconstrucion/DataGenerator/PointCloud2Depth/README.md). So it is not necessary to enter multiple point clouds.

Did the demo data fail during the normal estimation? By the way, the image shown [here](https://github.com/Haonan-DONG/awesome_indoor_reconstruction/blob/b953d1448f001f6a0d7b24e4a1d745682f539bc0/indoor_reconstrucion/README.md?plain=1#L36) is manually trimmed.

**Comment by Haonan-DONG** [comment]
Yes, the source code is designed for multiple point clouds. Thus, you should prepare the .mlp file for the pipeline. But the 4X4 matrix can be random value, for example, 
[[1,0,0,1]
 [0,1,0,1]
 [0,0,1,1]
 [0,0,0,1]].

It seems that the code goes fine with the demo data from eth3d and the warnings indicate those properties are missing compared to the data structure used by the source code, which will not influence the result. So just follow the structure of the demo data for your own data and you are ready to go. For multiple point clouds to generate the depth, the point clouds should be aligned with accurate pose in the .mlp file.

**Comment by Leestronger** [comment]
Thank you very much for your patient reply. It's very kind of you. (#^.^#)

**Comment by Haonan-DONG** [comment]
Any time! Issue is closed.

**Comment by Leestronger** [comment]
For point clouds without color, it seems impossible to complete the calculation and reconstruction of normal vector
